# version of docker compos
version: "3"

services: # containers to be run
    api: # api container
        build: .
        ports: # <port on localhost>:<port on container>
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        # env_file:
        #     - ./.env
        environment: # pass environment variables to container
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_NAME=postgres
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=password123
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        depends_on:
            - postgres

    postgres: # build postgres image as its own container
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password123
        volumes: # to save data
            - postgres-db:/var/lib/postgresql/data


volumes: # named volumes
    postgres-db: # multiple containers can reference named volumes