"""auto-vote

Revision ID: fccb33765770
Revises: 03fb462a0275
Create Date: 2021-12-31 16:21:10.315137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccb33765770'
down_revision = '03fb462a0275'
branch_labels = None
depends_on = None


# ran with alembic revision --auto-generate
# changed codes because alembic returnd different changes due to table names (incl. _testing in our examples)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes_testing",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts_testing.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["user_id"], ["users_testing.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("post_id", "user_id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("votes_testing")
    # ### end Alembic commands ###
